-- AlterTable
ALTER TABLE `admin` ADD COLUMN `role` ENUM('ADMIN', 'CUSTOMER', 'VENDOR') NOT NULL DEFAULT 'ADMIN';

-- AlterTable
ALTER TABLE `customer` ADD COLUMN `role` ENUM('ADMIN', 'CUSTOMER', 'VENDOR') NOT NULL DEFAULT 'CUSTOMER';

-- AlterTable
ALTER TABLE `vendor` ADD COLUMN `role` ENUM('ADMIN', 'CUSTOMER', 'VENDOR') NOT NULL DEFAULT 'VENDOR';
